<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Player;

class PlayerSeeder extends Seeder
{
    public function run(): void
    {
        Player::insert([
            [
                'name' => 'LeBron James',
                'team' => 'Lakers',
                'position' => 'SF',
                'image' => 'lebron.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=VAcxU6kR9cE',
                'afrobeats_track' => 'Burna Boy - Last Last',
                'points_per_game' => 27.3,
                'assists_per_game' => 7.4,
                'rebounds_per_game' => 7.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stephen Curry',
                'team' => 'Warriors',
                'position' => 'PG',
                'image' => 'curry.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=1QzPqb6u4c4',
                'afrobeats_track' => 'Wizkid - Essence',
                'points_per_game' => 29.5,
                'assists_per_game' => 6.2,
                'rebounds_per_game' => 5.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giannis Antetokounmpo',
                'team' => 'Bucks',
                'position' => 'PF',
                'image' => 'giannis.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=Di7EEDKsfPU',
                'afrobeats_track' => 'Davido - Feel',
                'points_per_game' => 28.1,
                'assists_per_game' => 5.9,
                'rebounds_per_game' => 11.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jayson Tatum',
                'team' => 'Celtics',
                'position' => 'SF',
                'image' => 'tatum.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=DLGr5FU5AoQ',
                'afrobeats_track' => 'Rema - Calm Down',
                'points_per_game' => 26.4,
                'assists_per_game' => 4.3,
                'rebounds_per_game' => 8.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kevin Durant',
                'team' => 'Suns',
                'position' => 'SF',
                'image' => 'durant.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=sM__tUnGgOA',
                'afrobeats_track' => 'Omah Lay - Soso',
                'points_per_game' => 27.9,
                'assists_per_game' => 5.6,
                'rebounds_per_game' => 6.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luka Dončić',
                'team' => 'Mavericks',
                'position' => 'PG',
                'image' => 'luka.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=fvhG8kzDNDI',
                'afrobeats_track' => 'Tems - Free Mind',
                'points_per_game' => 31.0,
                'assists_per_game' => 8.0,
                'rebounds_per_game' => 8.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joel Embiid',
                'team' => '76ers',
                'position' => 'C',
                'image' => 'embiid.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=TX7Kow8DZVg',
                'afrobeats_track' => 'Fireboy DML - Peru',
                'points_per_game' => 30.4,
                'assists_per_game' => 4.2,
                'rebounds_per_game' => 10.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ja Morant',
                'team' => 'Grizzlies',
                'position' => 'PG',
                'image' => 'ja.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=8biDYniXblY',
                'afrobeats_track' => 'Asake - Lonely At The Top',
                'points_per_game' => 26.2,
                'assists_per_game' => 7.1,
                'rebounds_per_game' => 5.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jimmy Butler',
                'team' => 'Heat',
                'position' => 'SF',
                'image' => 'butler.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=rUS0PH8kaRs',
                'afrobeats_track' => 'CKay - Love Nwantiti',
                'points_per_game' => 24.6,
                'assists_per_game' => 5.5,
                'rebounds_per_game' => 6.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Devin Booker',
                'team' => 'Suns',
                'position' => 'SG',
                'image' => 'booker.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=wAdCEVw4vx8',
                'afrobeats_track' => 'Joeboy - Alcohol',
                'points_per_game' => 26.1,
                'assists_per_game' => 4.4,
                'rebounds_per_game' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zion Williamson',
                'team' => 'Pelicans',
                'position' => 'PF',
                'image' => 'zion.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=3eRAGGHFZVY',
                'afrobeats_track' => 'Ayra Starr - Rush',
                'points_per_game' => 23.8,
                'assists_per_game' => 3.9,
                'rebounds_per_game' => 6.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Damian Lillard',
                'team' => 'Bucks',
                'position' => 'PG',
                'image' => 'lillard.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=tg3s2R5vjR0',
                'afrobeats_track' => 'Tiwa Savage - Somebody’s Son',
                'points_per_game' => 27.0,
                'assists_per_game' => 6.7,
                'rebounds_per_game' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anthony Edwards',
                'team' => 'Timberwolves',
                'position' => 'SG',
                'image' => 'edwards.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=dXROwE_bRFE',
                'afrobeats_track' => 'BNXN - Gwagalada',
                'points_per_game' => 25.4,
                'assists_per_game' => 4.1,
                'rebounds_per_game' => 5.0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kyrie Irving',
                'team' => 'Mavericks',
                'position' => 'PG',
                'image' => 'kyrie.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=QnRpn_2RMns',
                'afrobeats_track' => 'Lojay - Monalisa',
                'points_per_game' => 24.9,
                'assists_per_game' => 5.8,
                'rebounds_per_game' => 3.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Donovan Mitchell',
                'team' => 'Cavaliers',
                'position' => 'SG',
                'image' => 'mitchell.jpg',
                'highlight_url' => 'https://www.youtube.com/watch?v=KX7TZ52Txo4',
                'afrobeats_track' => 'Adekunle Gold - 5 Star',
                'points_per_game' => 27.8,
                'assists_per_game' => 4.5,
                'rebounds_per_game' => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
